### ISSUE TITLE
Unable to build yd-qgo

### ISSUE THREAD

**Issue by atolstoy** [slytomcat/yd-qgo#5]
I'm getting the following errors:
./qgui.go:19:2: imported and not used: "path"
./qgui.go:76:12: undefined: ok

Please provide instructions for compiling on modern Linux systems. Mine is Leap 15.2, with various Go versions from 1.4 to 1.14 (none of them worked).

**Comment by slytomcat** [comment]
It was some mistakes in the code. They are fixed now. Just update code from master branch and try again.

**Comment by atolstoy** [comment]
Thanks, it seems to work now!
